### ISSUE TITLE
Update to fish 3

### ISSUE THREAD

**Issue by lunaryorn** [lunaryorn/dotfiles#1]
See <https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.md>

## TODO

- [x] In `config.fish` replace `on_exit --on-process-exit %self` with the `fish_exit` events which emits rights before fish exits.
- [x] Replace `^` for stderr redirection with `2>` (`config.fish`, `prompt_battery_macos.fish`, and perhaps others)
- [x] Replace calls to `hostname` with the new `$hostname` variable if applicable (check whether `$hostname` is `hostname` or `hostname -f`).
- [x] Consider replacing `and` and `or` and `not` with the new `&&`, `||` and `!` respectively.
